### ISSUE TITLE
LookerSetup function does not check for port

### ISSUE THREAD

**Issue by kyeoh** [githoov/LookR#4]
Probably should be changed to this

 if (url.exists(paste("https://", host, ":", port, sep = "")

**Comment by kyeoh** [comment]
Actually, in other parts of the code it seems port 443 is hardcoded (?)

Might be better just change the host to 
  host = "host:port", 
Since it seems port = xxxx is ignored

**Comment by githoov** [comment]
@kyeoh Yeah—the setup function is misleading in that regard. I'm open to not having 443 hardcoded and be an actual parameter or not documenting port altogether.

**Comment by kyeoh** [comment]
host = "host:port" seems to work fine for me!

Have a question on how to add filter parameters though - although I get this message when I run the query: 
tablename.user_id:'00570000002nSX1AAM' has been applied as a filter

I still get the results for all user_ids

**Comment by githoov** [comment]
Interesting—can you send me your ```LookerQuery``` portion via email? scott@looker.com
